//
// Created by adria on 24/02/2019.
//

#ifndef SPACEINVADERS_KEYCODES_HPP
#define SPACEINVADERS_KEYCODES_HPP

namespace GameEngine{

    enum class MouseButton {
        LEFT,
        RIGHT,
        MIDDLE
    };

    enum class KeyCode
    {
        KEY_UNKNOWN,
        KEY_RETURN,
        KEY_ESCAPE,
        KEY_BACKSPACE,
        KEY_TAB,
        KEY_SPACE,
        KEY_EXCLAIM,
        KEY_QUOTEDBL,
        KEY_HASH,
        KEY_PERCENT,
        KEY_DOLLAR,
        KEY_AMPERSAND,
        KEY_QUOTE,
        KEY_LEFTPAREN,
        KEY_RIGHTPAREN,
        KEY_ASTERISK,
        KEY_PLUS,
        KEY_COMMA,
        KEY_MINUS,
        KEY_PERIOD,
        KEY_SLASH,
        KEY_0,
        KEY_1,
        KEY_2,
        KEY_3,
        KEY_4,
        KEY_5,
        KEY_6,
        KEY_7,
        KEY_8,
        KEY_9,
        KEY_COLON,
        KEY_SEMICOLON,
        KEY_LESS,
        KEY_EQUALS,
        KEY_GREATER,
        KEY_QUESTION,
        KEY_AT,
        KEY_LEFTBRACKET,
        KEY_BACKSLASH ,
        KEY_RIGHTBRACKET,
        KEY_CARET,
        KEY_UNDERSCORE,
        KEY_BACKQUOTE,

        KEY_a,
        KEY_b,
        KEY_c,
        KEY_d,
        KEY_e,
        KEY_f,
        KEY_g,
        KEY_h,
        KEY_i,
        KEY_j,
        KEY_k,
        KEY_l,
        KEY_m,
        KEY_n,
        KEY_o,
        KEY_p,
        KEY_q,
        KEY_r,
        KEY_s,
        KEY_t,
        KEY_u,
        KEY_v,
        KEY_w,
        KEY_x,
        KEY_y,
        KEY_z,

        KEY_F1,
        KEY_F2,
        KEY_F3,
        KEY_F4,
        KEY_F5,
        KEY_F6,
        KEY_F7,
        KEY_F8,
        KEY_F9,
        KEY_F10,
        KEY_F11,
        KEY_F12,

        KEY_PRINTSCREEN,
        KEY_SCROLLLOCK,
        KEY_PAUSE,
        KEY_INSERT,
        KEY_HOME,
        KEY_PAGEUP,
        KEY_DELETE,
        KEY_END,
        KEY_PAGEDOWN,
        KEY_RIGHT,
        KEY_LEFT,
        KEY_DOWN,
        KEY_UP,

        KEY_LCTRL,
        KEY_LSHIFT,
        KEY_LALT,
        KEY_RCTRL,
        KEY_RSHIFT,
        KEY_RALT,

        KEY_NUMLOCKCLEAR,
        NUMPAD_DIVIDE,
        NUMPAD_MULTIPLY,
        NUMPAD_MINUS,
        NUMPAD_PLUS,
        NUMPAD_ENTER,
        NUMPAD_1,
        NUMPAD_2,
        NUMPAD_3,
        NUMPAD_4,
        NUMPAD_5,
        NUMPAD_6,
        NUMPAD_7,
        NUMPAD_8,
        NUMPAD_9,
        NUMPAD_0,
        NUMPAD_PERIOD
    };
}

#endif //SPACEINVADERS_KEYCODES_HPP
